version: "3.9"

services:
  database:
    image: postgres
    container_name: liven-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=liven
      - POSTGRES_PASSWORD=liven
      - POSTGRES_DB=liven
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: liven-server
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
